# Commands to run services below:
# docker-compose run --rm --service-ports app
# docker-compose up -d db
# docker-compose run --rm backtest
# Enter database via terminal:
# docker exec -it noshirt-postgres psql -U postgres -d noshirt

services:
  app:
    build: .
    container_name: noshirt_app
    volumes:
      - .:/noshirt
    environment:
      - PYTHONPATH=/noshirt/main
      - POSTGRES_DB=noshirt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: python main/prod/app.py
    ports:
      - "8080:80"
    depends_on:
      - db

  api:
    build: .
    container_name: noshirt_api
    volumes:
      - .:/noshirt
    environment:
      - PYTHONPATH=/noshirt/main
      - POSTGRES_DB=noshirt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: uvicorn main.prod.api:api --reload --host=0.0.0.0
    ports:
      - "8000:8000"
    depends_on:
      - db

  telegram:
    build: .
    container_name: noshirt_telegram
    volumes:
      - .:/noshirt
    environment:
      - ENVIRONMENT=production
      - TELEGRAM_API_KEY=${TELEGRAM_API_KEY}
      - EC2_PUBLIC_IP=${EC2_PUBLIC_IP}
      - PYTHONPATH=/noshirt/main
      - POSTGRES_DB=noshirt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: python main/prod/telegram_bot.py
    depends_on:
      - db
    
  backtest:
    build: .
    container_name: noshirt_backtest
    volumes:
      - .:/noshirt
    environment:
      - PYTHONPATH=/noshirt/main
      - POSTGRES_DB=noshirt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_HOST=db
    command: python main/backtest/app.py
    ports:
      - "8081:81"
    depends_on:
      - db

  db:
    image: postgres
    container_name: noshirt-postgres
    environment:
      - POSTGRES_DB=noshirt
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - noshirt_postgres_data:/var/lib/postgresql/data
      - ./main/prod/resources/db:/resources/prod
      - ./main/backtest/resources/db:/resources/backtest
    ports:
      - "5431:5432"
    # entrypoint: ["bin/bash", "/resources/init-db.sh"]

volumes:
  noshirt_postgres_data:
